name: C++ (GNAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  dev-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          tags: ${{ github.sha }}

  build:
    needs: dev-environment
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: gprbuild -j0 -p service.gpr

    - name: Unit Tests
      run: make unit-tests
