name: C++ (GNAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  dev-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/admajonse/cpp-gnat
          tags: type=sha,enable=true,prefix=,suffix=,format=long

      - name: Build and push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build:
    needs: dev-environment
    runs-on: ubuntu-latest
    container: ghcr.io/admajonse/cpp-gnat:${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: get username
      run: whoami

    - name: Print PATH
      run: echo $PATH

    - name: list /opt
      run: ls /opt

    - name: list /opt/gnat
      run: ls /opt/gnat

    - name: list /etc/profile.d
      run: ls /etc/profile.d

    - name: check gprbuild
      run: which gprbuild

    - name: Build
      run: make build

    - name: Unit Tests
      run: make unit-tests
